### ISSUE TITLE
Question: Does this action toggle the state unconditionally?

### ISSUE THREAD

**Issue by willvedd** [benjefferies/branch-protection-bot#1]
Not an issue, and excuse me if this is made clear somewhere, but it seems like this action toggles the state of the setting rather than explicitly setting it to on or off. This is probably fine in most cases but I'm worried about cases where the first step succeeds, turning the setting off, then my build exits without turning it back on. So when I go to build again, I'm flipping it from off=>on. Does this action consider this scenario and prevent unintended states of this setting?

**Comment by willvedd** [comment]
Realized I could answer my own question if I just looked at the code! So yes, the `toggle_enforce_admin` toggles that setting. Would you consider an option to define these options explicitly? This is a setting that I need to ensure doesn't fall into some unexpected state.

**Comment by benjefferies** [comment]
@willvedd I've added and tested in locally. Haven't been able to test in a github actions workflow yet but I'll give it a go later

**Comment by benjefferies** [comment]
I broke some stuff with the commits on the weekend but I've fixed it, added tests and created a workflow to test it

**Comment by willvedd** [comment]
@benjefferies Nice! Thanks for considering this feature. I'm going to try this and see if it solves our issues.
