### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by jeffhubLR** [benjefferies/branch-protection-bot#16]
A Github Actions run today resulted in the error described.

It seems to be a combination of the recently-released python:3.7.8-slim-stretch image (which caused an update to python:3.7-slim-stretch being used in the Dockerfile in this project) along with this stackoverflow post:
https://stackoverflow.com/questions/13967428/importerror-no-module-named-six

Easiest fix would be to revert to python:3.7.7-slim-stretch in the Dockerfile.

**Comment by benjefferies** [comment]
pipenv just released a new version today so it could be related to this. I will investigate

**Comment by benjefferies** [comment]
@jeffhubLR Looks like pinning that docker image didn't fix it https://github.com/benjefferies/branch-protection-bot/runs/981180467?check_suite_focus=true

**Comment by jeffhubLR** [comment]
Thanks for the responsiveness, @benjefferies . Sorry my initial suggestion didn't work. I know it breaks the nice pipenv workflow, but a `RUN pip install six` [here](https://github.com/benjefferies/branch-protection-bot/blob/master/Dockerfile#L18) is my other thought.

**Comment by benjefferies** [comment]
I'll give it a go. If not I'll pin pipenv to the previous version for now to unblock

**Comment by jeffhubLR** [comment]
nevermind. that doesn't seem to resolve it.

**Comment by bengry** [comment]
@benjefferies does the fix in #17 require a new tag? We're currently using the action `@1.0.4`, but since the fix is not there I think we'll need to update to use `@master`, though I'd really prefer to use anl tag like `1.0.4`.

**Comment by benjefferies** [comment]
https://github.com/benjefferies/branch-protection-bot/releases/tag/v1.0.5
