### ISSUE TITLE
Build times of >45 seconds in CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [benjefferies/branch-protection-bot#31]
I'm repeatedly seeing `Build benjefferies/branch-protection-bot@1.0.7` taking almost a minute. [Example build of 47 seconds](https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/3767686080/jobs/6405461778).

Is there any way to cut down on this time? E.g. going with a prebuilt container, and/or including fewer dependencies? (sorry if those suggestions are totally useless; I neither use Docker nor Python  in my day-to-day)

**Comment by benjefferies** [comment]
Hey @JoshuaKGoldberg, I'm all up for making it a prebuilt image although looking at you logs, it only took one second (maybe caching after first run?)
