### ISSUE TITLE
stretch release no longer exists in debian ftp

### ISSUE THREAD

**Issue by litaocdl** [benjefferies/branch-protection-bot#33]
http://ftp.debian.org/debian/dists/stretch  not exists anymore 
can we upgrade to use `python:3.7-slim-buster` or `3.7-slim-bullseye` as base in docker file

**Comment by litaocdl** [comment]
pr is merged https://github.com/benjefferies/branch-protection-bot/pull/34
@benjefferies can we trigger a new release ?

**Comment by benjefferies** [comment]
> pr is merged https://github.com/benjefferies/branch-protection-bot/pull/34
> @benjefferies can we trigger a new release ?

Yeah give me and hour and it'll be done 👍

**Comment by benjefferies** [comment]
@litaocdl https://github.com/benjefferies/branch-protection-bot/releases/tag/1.0.8
