### ISSUE TITLE
Doesn't work on Mac actions

### ISSUE THREAD

**Issue by hipstersmoothie** [benjefferies/branch-protection-bot#35]
![CleanShot 2023-05-30 at 16 37 26](https://github.com/benjefferies/branch-protection-bot/assets/1192452/e9d6d0c5-cb21-4caa-a7e8-844b3691a481)

**Comment by benjefferies** [comment]
Looks like github doesn't support docker desktop in their build runners. You could work around this using `runs-on:` for now https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
