### ISSUE TITLE
This should work with unprotected branch too

### ISSUE THREAD

**Issue by kgouraw** [benjefferies/branch-protection-bot#38]
This works very well but shouldn't throw an error if we apply this with an unprotected branch.

**Comment by benjefferies** [comment]
Thanks for the feedback. Can you provide the error or a link to an example github action workflow?

**Comment by kgouraw** [comment]
> Thanks for the feedback. Can you provide the error or a link to an example github action workflow?

I get below error with unprotected branch.


![image](https://github.com/benjefferies/branch-protection-bot/assets/14645617/ce650d95-ed50-4446-b272-fb587a25c3c6)

**Comment by benjefferies** [comment]
Out of interest why would you want to apply this to a branch that isn't protected? Is it because you have the same github workflow dynamically passing in the branch name?
