### ISSUE TITLE
Which scopes does the personal access token require?

### ISSUE THREAD

**Issue by d-luk** [benjefferies/branch-protection-bot#9]

**Comment by benjefferies** [comment]
You'll need to give full repo access

**Comment by d-luk** [comment]
Thanks. I would suggest mentioning this in the README.

**Comment by benjefferies** [comment]
https://github.com/benjefferies/branch-protection-bot/compare/master...benjefferies-patch-2?quick_pull=1 @d-luk

**Comment by itay-grudev** [comment]
@benjefferies Which scopes are required, because Classic tokens with repo only doesn't work.

**Comment by itay-grudev** [comment]
I managed to get it working with the new Fine Grained Access Tokens, with only the following permissions:

**Administration**: Read & Write
**Metadata**: Read Only

![image](https://github.com/benjefferies/branch-protection-bot/assets/2123767/c5fc70ca-e0d5-49f0-8287-b21cea18b364)

This is the perfect setup in my opinion.
